server:
  port: 8000
  
spring:
  application:
    name: microservice-provider-user
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: true
  datasource:
     platform: h2
     schema: classpath:schema.sql  
     data: classpath:data.sql
           
logging:
  level: INFO
  org.hibernate: INFO
  org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
  com.ly: DEBUG
  
eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/
      
  instance:
    prefer-ip-address: true